### ISSUE TITLE
Error: undefined method `message_count' for #<Aws::SQS::QueuePoller::PollerStats

### ISSUE THREAD

**Issue by cdenneen** [logstash-plugins/logstash-input-sqs#22]
``` ruby
A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::SQS access_key_id=>"AAAAAAA", secret_access_key=>"ZZZZZZ", queue=>"logstashbrokerqueue", region=>"us-east-1", threads=>4, debug=>false, codec=><LogStash::Codecs::JSON charset=>"UTF-8">, polling_frequency=>20>
  Error: undefined method `message_count' for #<Aws::SQS::QueuePoller::PollerStats:0x160b6c12>
  Exception: NoMethodError
  Stack: /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-sqs-1.1.0/lib/logstash/inputs/sqs.rb:148:in `run'
/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.1.33/lib/aws-sdk-resources/services/sqs/queue_poller.rb:416:in `yield_messages'
/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.1.33/lib/aws-sdk-resources/services/sqs/queue_poller.rb:405:in `process_messages'
org/jruby/RubyKernel.java:1242:in `catch'
/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.1.33/lib/aws-sdk-resources/services/sqs/queue_poller.rb:404:in `process_messages'
/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.1.33/lib/aws-sdk-resources/services/sqs/queue_poller.rb:336:in `poll'
org/jruby/RubyKernel.java:1479:in `loop'
/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.1.33/lib/aws-sdk-resources/services/sqs/queue_poller.rb:331:in `poll'
org/jruby/RubyKernel.java:1242:in `catch'
/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.1.33/lib/aws-sdk-resources/services/sqs/queue_poller.rb:330:in `poll'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-sqs-1.1.0/lib/logstash/inputs/sqs.rb:143:in `run'
org/jruby/RubyProc.java:271:in `call'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-sqs-1.1.0/lib/logstash/inputs/sqs.rb:166:in `run_with_backoff'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-sqs-1.1.0/lib/logstash/inputs/sqs.rb:142:in `run'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.5-java/lib/logstash/pipeline.rb:177:in `inputworker'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.5-java/lib/logstash/pipeline.rb:171:in `start_input' {:level=>:error, :file=>"logstash/pipeline.rb", :line=>"182", :method=>"inputworker"}
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-sqs-1.1.0/lib/logstash/inputs/sqs.rb:148:in `run'
/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.1.33/lib/aws-sdk-resources/services/sqs/queue_poller.rb:416:in `yield_messages'
/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.1.33/lib/aws-sdk-resources/services/sqs/queue_poller.rb:405:in `process_messages'
org/jruby/RubyKernel.java:1242:in `catch'
/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.1.33/lib/aws-sdk-resources/services/sqs/queue_poller.rb:404:in `process_messages'
/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.1.33/lib/aws-sdk-resources/services/sqs/queue_poller.rb:336:in `poll'
org/jruby/RubyKernel.java:1479:in `loop'
/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.1.33/lib/aws-sdk-resources/services/sqs/queue_poller.rb:331:in `poll'
org/jruby/RubyKernel.java:1242:in `catch'
/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.1.33/lib/aws-sdk-resources/services/sqs/queue_poller.rb:330:in `poll'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-sqs-1.1.0/lib/logstash/inputs/sqs.rb:143:in `run'
org/jruby/RubyProc.java:271:in `call'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-sqs-1.1.0/lib/logstash/inputs/sqs.rb:166:in `run_with_backoff'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-sqs-1.1.0/lib/logstash/inputs/sqs.rb:142:in `run'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.5-java/lib/logstash/pipeline.rb:177:in `inputworker'
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.5-java/lib/logstash/pipeline.rb:171:in `start_input'
```

**Comment by ph** [comment]
Woa! my bad! will fix this.

https://github.com/logstash-plugins/logstash-input-sqs/commit/db16e9d406639b79a4abfeaf180f159733298ee7#commitcomment-14454563
