### ISSUE TITLE
SQS Plugin seems to not work on docker

### ISSUE THREAD

**Issue by Yorinh** [logstash-plugins/logstash-input-sqs#50]
Hello !

We got an issue with AWS SQS Input plugin, we are trying to use the plugin in a redhat from AWS with Logstash 6.5 installed by ourself on a docker environnement. (we are not using AWS managed services)

When we are trying to start the docker, we got those errors (with debbug mode on): 
```
[2019-01-07T17:57:58,715][DEBUG][logstash.agent           ] starting pipeline {:id=>"main"}
[2019-01-07T17:57:58,719][INFO ][logstash.pipeline        ] Starting pipeline {"id"=>"main", "pipeline.workers"=>2, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>250}
[2019-01-07T17:57:58,729][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {"exception"=>"undefined method `to_hash' for []:Array", "backtrace"=>["(eval):19:in `filter_func'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:398:in `filter_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:379:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:342:in `start_workers'"]}
[2019-01-07T17:57:58,739][INFO ][logstash.inputs.sqs      ] Registering SQS input {:queue=>"SQS-Logstash-bit"}
[2019-01-07T17:57:58,750][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {"exception"=>"undefined method `to_hash' for []:Array", "backtrace"=>["(eval):19:in `filter_func'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:398:in `filter_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:379:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:342:in `start_workers'"]}
[2019-01-07T17:57:58,910][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<NoMethodError: undefined method `to_hash' for []:Array>, :backtrace=>["(eval):19:in `filter_func'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:398:in `filter_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:379:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:342:in `start_workers'"]}
```
We first thought of a problem with AWS connectivity or user right, so we tried to use AWSCLI in the same docker container and informations to directly poll the SQS Queue wishing that will also fail but... it worked perfectly. 
Also, we tried to get the url queue with the same informations as the input configuration and it also worked.

Finaly we installed logstash directly on the host and it's working with the same configuration.

Any idea why ?

Here is our logstash configuration : 

```
input {
        sqs {
                id => "SQS-Logstash-bit"
                access_key_id => "SuperAccessKeyId"
                secret_access_key => "SuperSecretAccessKey"
                queue => "SQS-Logstash-bit"
                region => "eu-west-1"
                threads => 1
        }
}

filter {
}


output {
 stdout { codec => rubydebug {  metadata => true } }
}
```

**Comment by Yorinh** [comment]
We finally found the issue... It was simply the Logstash version in the dockerfile, we used 5.5.0 instead of 5.6.0...
